[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/process-sale"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[dev]
  port = 8888
  targetPort = 8888
  publish = "."
